services:
  - type: web
    name: mtaa-connect-backend
    env: python
    plan: free
    buildCommand: |
      bash build.sh
    startCommand: |
      python manage.py migrate
      python manage.py initadmin
      gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
